# Generated by Django 2.2.6 on 2019-10-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='submitter',
        ),
    ]
