# Generated by Django 2.2.6 on 2019-10-24 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_remove_album_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_submitted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
