# Generated by Django 2.2.6 on 2019-10-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20191024_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='coverUrl',
            new_name='cover_url',
        ),
    ]
