# Generated by Django 2.2.6 on 2019-10-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20191024_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='href',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
