# Generated by Django 2.2.6 on 2019-10-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_auto_20191024_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_url',
            field=models.CharField(default='https://i.scdn.co/image/e5f5a50956c2c7dd5411051ca507b4f771d6d816', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='href',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
