# Generated by Django 2.2.6 on 2019-10-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_auto_20191024_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
