# Generated by Django 2.2.6 on 2019-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_auto_20191025_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='additional_thoughts',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
